### ISSUE TITLE
Virsorter2 like feature

### ISSUE THREAD

**Issue by balazshorvathreal** [ChengPENG-wolf/ViraLM#2]
Would it be possible to implement a useful feature (like in Virsorter2) where the output is not just a table, but a set of ranking based virus.fasta/non-virus.fasta binnings (perhaps a score based threshold could be added). This would avoid the use of external, text based sequence filters (e.g. BBDUK / awk) and would greatly simplify pipelining.

Best regards: B

**Comment by ChengPENG-wolf** [comment]
Thanks for your suggestion. I have updated the `viralm.py` file. There are two updates. First, the results in `result_INPUT_FA_NAME.csv` are ranked by the score. Second, ViraLM will produce a `virus_INPUT_FA_NAME.fasta` file that collects all the identified viral sequences that meet the user-specified threshold.

Best regards

**Comment by balazshorvathreal** [comment]
Thank you very much, you respond amazingly fast and offer the solution :)
