### ISSUE TITLE
Ablation Study

### ISSUE THREAD

**Issue by a1678019300** [ChengPENG-wolf/ViraLM#3]
Dear Cheng Peng:
Hello! Thank you for the excellent work you made : ViraLM. Can you share the code for the ablation experiment? I am more interested in the part where the pre-training weights are removed and the training is done using randomly initialized weights. Appreciate if you can share it.
Best wishes.
Gao Peng.

**Comment by ChengPENG-wolf** [comment]
Dear Gao Peng,

**Comment by ChengPENG-wolf** [comment]
Dear Gao Peng,
You can randomly initialize the weights through the following code:

```
model = randomize_model(model)
def randomize_model(model):
    for module_ in model.named_modules():
        if isinstance(module_[1],(torch.nn.Linear, torch.nn.Embedding)):
            module_[1].weight.data.normal_(mean=0.0, std=model.config.initializer_range)
        elif isinstance(module_[1], torch.nn.LayerNorm):
            module_[1].bias.data.zero_()
            module_[1].weight.data.fill_(1.0)
        if isinstance(module_[1], torch.nn.Linear) and module_[1].bias is not None:
            module_[1].bias.data.zero_()
    return model
```

**Comment by a1678019300** [comment]
Dear Cheng Peng:
Thank you for your timely response!
